CREATE TABLE `templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(200) NOT NULL,
	`slug` varchar(200) NOT NULL,
	`description` text,
	`notes` text,
	`website_url` varchar(500),
	`source_url` varchar(500),
	`author_name` varchar(200),
	`author_url` varchar(500),
	`author_image` varchar(500),
	`cover_image` varchar(500),
	`mobile_image` varchar(500),
	`images` json DEFAULT ('[]'),
	`sections` json DEFAULT ('[]'),
	`features` json DEFAULT ('[]'),
	`categories` json DEFAULT ('[]'),
	`styles` json DEFAULT ('[]'),
	`typefaces` json DEFAULT ('[]'),
	`tags` json DEFAULT ('[]'),
	`colors` json DEFAULT ('[]'),
	`stack` json DEFAULT ('[]'),
	`published_at` date,
	`price` enum('free','paid'),
	`rating` int,
	`is_favorite` boolean NOT NULL DEFAULT false,
	`order` int NOT NULL DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `templates_id` PRIMARY KEY(`id`),
	CONSTRAINT `templates_slug_unique` UNIQUE(`slug`)
);
